version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    restart: always
    volumes:
      - .:/src:cached
    depends_on:
      - db
    ports:
      - "${PORT}:${PORT}"  
  db:
    image: postgres:latest
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env

volumes:
  pgdata: