version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-lumi
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"    
    ports:
      - "5432:5432"               
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: