-- AlterTable
ALTER TABLE "bill" ALTER COLUMN "energy_send_unit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "energy_icms_unit" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "energy_unit" SET DATA TYPE DOUBLE PRECISION;
